$axure.loadCurrentPage({
  "url":"快速通道-用户登录-登录前.html",
  "generationDate":new Date(1403073192081.95),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"340cbe48d3fe4892ab1fbcf9c1cb95b6",
    "type":"Axure:Page",
    "name":"快速通道-用户登录-登录前",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"7327d4680daa4d87a377e98149ccc48a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1342,
              "height":3808}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"22a1ac6679744c90b709b5de8dee563b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1342,
                  "height":3808}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/快速通道-用户登录-登录前/u0.jpg"}}]}},
  "masters":{
},
  "objectPaths":{
    "7327d4680daa4d87a377e98149ccc48a":{
      "scriptId":"u0"},
    "22a1ac6679744c90b709b5de8dee563b":{
      "scriptId":"u1"}}});