$axure.loadCurrentPage({
  "url":"我的投资（已预约项目）.html",
  "generationDate":new Date(1403073205173.7),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b537f46ac9474f3dbc3e2ad016011f04",
    "type":"Axure:Page",
    "name":"我的投资（已预约项目）",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4d0dea9589954cee80855d7293489dd6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1366,
              "height":1032}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f7e43cdc64fe47f0bf302e929e06e590",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1366,
                  "height":1032}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的投资（已预约项目）/u0.jpg"}}]}},
  "masters":{
},
  "objectPaths":{
    "4d0dea9589954cee80855d7293489dd6":{
      "scriptId":"u0"},
    "f7e43cdc64fe47f0bf302e929e06e590":{
      "scriptId":"u1"}}});