$axure.loadCurrentPage({
  "url":"第四步-成功.html",
  "generationDate":new Date(1403073196300.2),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"04e103b859614502a8a7d953c3299eb1",
    "type":"Axure:Page",
    "name":"第四步-成功",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"15e195891a3a4d139a6f7f047fd372b5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1342,
              "height":864}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3b26cdb73db444f9ada6cb4aacf7c500",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1342,
                  "height":864}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/第四步-成功/u0.jpg"}}]}},
  "masters":{
},
  "objectPaths":{
    "15e195891a3a4d139a6f7f047fd372b5":{
      "scriptId":"u0"},
    "3b26cdb73db444f9ada6cb4aacf7c500":{
      "scriptId":"u1"}}});