$axure.loadCurrentPage({
  "url":"搜索-资讯.html",
  "generationDate":new Date(1403073210078.98),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"d732bf5ceff14572851f2cfb5f554764",
    "type":"Axure:Page",
    "name":"搜索-资讯",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"d8513fff83924e8fb852db6fdf99d292",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1342,
              "height":2400}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ca1ad7ef28d4f5ab0e02dada677a8c8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1342,
                  "height":2400}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/搜索-资讯/u0.jpg"}}]}},
  "masters":{
},
  "objectPaths":{
    "d8513fff83924e8fb852db6fdf99d292":{
      "scriptId":"u0"},
    "2ca1ad7ef28d4f5ab0e02dada677a8c8":{
      "scriptId":"u1"}}});