$axure.loadCurrentPage({
  "url":"专题策划.html",
  "generationDate":new Date(1403073204676.67),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"9d0d0aa8f95b481690d6016aa6089948",
    "type":"Axure:Page",
    "name":"专题策划",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"23826139165b46e3860cbecd91353344",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1342,
              "height":1998}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"48dc56cf52aa4c62aeb34279d8b3d25c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1342,
                  "height":1998}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/专题策划/u0.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "23826139165b46e3860cbecd91353344":{
      "scriptId":"u0"},
    "48dc56cf52aa4c62aeb34279d8b3d25c":{
      "scriptId":"u1"}}});