$axure.loadCurrentPage({
  "url":"产品详情.html",
  "generationDate":new Date(1403073198825.34),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"9059f7926663433285e7cf5467b7beba",
    "type":"Axure:Page",
    "name":"产品详情",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e998f99d8cb6424d82d2c83a24cd3ac7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1342,
              "height":2988}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1f344f11a3ff4ad78703f70061bf0fe2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1342,
                  "height":2988}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/产品详情/u0.jpg"}}]}},
  "masters":{
},
  "objectPaths":{
    "e998f99d8cb6424d82d2c83a24cd3ac7":{
      "scriptId":"u0"},
    "1f344f11a3ff4ad78703f70061bf0fe2":{
      "scriptId":"u1"}}});