$axure.loadCurrentPage({
  "url":"注册校验邮箱.html",
  "generationDate":new Date(1403073194613.1),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"118ee43e8e134736b0bb517bf94525f2",
    "type":"Axure:Page",
    "name":"注册校验邮箱",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"8c0b39d6bda1402aad386f885a5b2d47",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1366,
              "height":1000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0489268221d04c37a59a542bb620752d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1366,
                  "height":1000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册校验邮箱/u0.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "8c0b39d6bda1402aad386f885a5b2d47":{
      "scriptId":"u0"},
    "0489268221d04c37a59a542bb620752d":{
      "scriptId":"u1"}}});