$axure.loadCurrentPage({
  "url":"最新动态.html",
  "generationDate":new Date(1403073211039.04),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"0fc93f409c2f4ad98340c3035ad63dbf",
    "type":"Axure:Page",
    "name":"最新动态",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"0b40282ae8d84dbbb30aeba984fddb71",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1366,
              "height":1242}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ebaecc7fb54846929ce673dd3ef4c6ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1366,
                  "height":1242}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/最新动态/u0.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "0b40282ae8d84dbbb30aeba984fddb71":{
      "scriptId":"u0"},
    "ebaecc7fb54846929ce673dd3ef4c6ad":{
      "scriptId":"u1"}}});