$axure.loadCurrentPage({
  "url":"搜索-产品.html",
  "generationDate":new Date(1403073209801.97),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"0b7b645a78c942679b3af5068a3bad32",
    "type":"Axure:Page",
    "name":"搜索-产品",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"5252bf50b68d4a8d8fb3aab6e71b5044",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1342,
              "height":2131}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8aea51197e9e407385907063ee5b9fce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1342,
                  "height":2131}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/搜索-产品/u0.jpg"}}]}},
  "masters":{
},
  "objectPaths":{
    "5252bf50b68d4a8d8fb3aab6e71b5044":{
      "scriptId":"u0"},
    "8aea51197e9e407385907063ee5b9fce":{
      "scriptId":"u1"}}});