$axure.loadCurrentPage({
  "url":"快速通道-看过的和收藏的-产品.html",
  "generationDate":new Date(1403073189925.83),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"af561dcfda6d4a7c8b09e305aa9b2a86",
    "type":"Axure:Page",
    "name":"快速通道-看过的和收藏的-产品",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"9f5be9667304438b9ac4e8eefc496702",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1342,
              "height":3808}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94f6449d77a84f4c8cf241205e71ec6d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1342,
                  "height":3808}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/快速通道-看过的和收藏的-产品/u0.jpg"}}]}},
  "masters":{
},
  "objectPaths":{
    "9f5be9667304438b9ac4e8eefc496702":{
      "scriptId":"u0"},
    "94f6449d77a84f4c8cf241205e71ec6d":{
      "scriptId":"u1"}}});