$axure.loadCurrentPage({
  "url":"注册.html",
  "generationDate":new Date(1403073194142.07),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"181d9e26a76a4a7eae5311a706e420d5",
    "type":"Axure:Page",
    "name":"注册",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"32bdec314f1d412a8064b81b93efba5c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1366,
              "height":1000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ebec9bb5984c447c92080d208c0e485a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1366,
                  "height":1000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u0.jpg"}}]}},
  "masters":{
},
  "objectPaths":{
    "32bdec314f1d412a8064b81b93efba5c":{
      "scriptId":"u0"},
    "ebec9bb5984c447c92080d208c0e485a":{
      "scriptId":"u1"}}});