$axure.loadCurrentPage({
  "url":"直营店.html",
  "generationDate":new Date(1403073199137.36),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"26b227d12f14417c9efd377fbd303072",
    "type":"Axure:Page",
    "name":"直营店",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e07b018b7b0a4be4848e6a54561fdcd2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1342,
              "height":3438}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"020fada52a244994bd7dcbabb075fb2e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1342,
                  "height":3438}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/直营店/u0.jpg"}}]}},
  "masters":{
},
  "objectPaths":{
    "e07b018b7b0a4be4848e6a54561fdcd2":{
      "scriptId":"u0"},
    "020fada52a244994bd7dcbabb075fb2e":{
      "scriptId":"u1"}}});