$axure.loadCurrentPage({
  "url":"顶部-大资管.html",
  "generationDate":new Date(1403073188196.73),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"f1464eea56a741d09241dcd87f7c9b55",
    "type":"Axure:Page",
    "name":"顶部-大资管",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4de606fe29b7432d9f9f5fce9c9098b4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1342,
              "height":3900}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b59663243fa4020a3f135d89f179af3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1342,
                  "height":3900}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/顶部-大资管/u0.jpg"}}]}},
  "masters":{
},
  "objectPaths":{
    "4de606fe29b7432d9f9f5fce9c9098b4":{
      "scriptId":"u0"},
    "9b59663243fa4020a3f135d89f179af3":{
      "scriptId":"u1"}}});