$axure.loadCurrentPage({
  "url":"活动图片轮播页.html",
  "generationDate":new Date(1403073204108.64),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"ef0cf51e51dd49778dc6664060f5feac",
    "type":"Axure:Page",
    "name":"活动图片轮播页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"dc8f66e74ab74e5aa77525f1407b39ff",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1342,
              "height":2013}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67ebcfdaa18d41e8ab51dc74ce72a6bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1342,
                  "height":2013}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动图片轮播页/u0.jpg"}}]}},
  "masters":{
},
  "objectPaths":{
    "dc8f66e74ab74e5aa77525f1407b39ff":{
      "scriptId":"u0"},
    "67ebcfdaa18d41e8ab51dc74ce72a6bd":{
      "scriptId":"u1"}}});