$axure.loadCurrentPage({
  "url":"快速通道-用户登录-登录后.html",
  "generationDate":new Date(1403073192897),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"29cd113d79774a6cab68f49435660cfe",
    "type":"Axure:Page",
    "name":"快速通道-用户登录-登录后",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"30a8363b5b484135a7f4e50f9a553984",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1342,
              "height":3808}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ab7b66882e9484eb6f4369a7de3fd63",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1342,
                  "height":3808}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/快速通道-用户登录-登录后/u0.jpg"}}]}},
  "masters":{
},
  "objectPaths":{
    "30a8363b5b484135a7f4e50f9a553984":{
      "scriptId":"u0"},
    "2ab7b66882e9484eb6f4369a7de3fd63":{
      "scriptId":"u1"}}});