$axure.loadCurrentPage({
  "url":"预约-充值.html",
  "generationDate":new Date(1403073216069.33),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"545a680befd545cfa6bdc4b9e1584761",
    "type":"Axure:Page",
    "name":"预约-充值",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f1f66f613e2b498f9e76e166f0c854e5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1342,
              "height":887}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1806c45eef5f463dbabb6b96eaeb7f28",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1342,
                  "height":887}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预约-充值/u0.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "f1f66f613e2b498f9e76e166f0c854e5":{
      "scriptId":"u0"},
    "1806c45eef5f463dbabb6b96eaeb7f28":{
      "scriptId":"u1"}}});