$axure.loadCurrentPage({
  "url":"快速通道-二维码.html",
  "generationDate":new Date(1403073193608.04),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"8305bc9c2d4c4c92b6c23d3d7f7363b6",
    "type":"Axure:Page",
    "name":"快速通道-二维码",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"649a8ed687fa425b8f3d4b481c179856",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1342,
              "height":3808}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a2e7514fa960491fa571b3a11db99cdb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1342,
                  "height":3808}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/快速通道-二维码/u0.jpg"}}]}},
  "masters":{
},
  "objectPaths":{
    "649a8ed687fa425b8f3d4b481c179856":{
      "scriptId":"u0"},
    "a2e7514fa960491fa571b3a11db99cdb":{
      "scriptId":"u1"}}});