$axure.loadCurrentPage({
  "url":"注册校验手机.html",
  "generationDate":new Date(1403073194394.09),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"4a82f9eab9ee451ea1ab23cf7ad69ad3",
    "type":"Axure:Page",
    "name":"注册校验手机",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"035293f249504fa882ceb4a2c0ae7008",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1366,
              "height":1000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f61961efdec479898fe9f68334b32a0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1366,
                  "height":1000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册校验手机/u0.jpg"}}]}},
  "masters":{
},
  "objectPaths":{
    "035293f249504fa882ceb4a2c0ae7008":{
      "scriptId":"u0"},
    "8f61961efdec479898fe9f68334b32a0":{
      "scriptId":"u1"}}});