$axure.loadCurrentPage({
  "url":"资管产品列表-最近浏览.html",
  "generationDate":new Date(1403073197731.28),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"af25d13f740741c99d8cd2af82b404a0",
    "type":"Axure:Page",
    "name":"资管产品列表-最近浏览",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"468f6bb9ab5948a286beddbf398d580e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1342,
              "height":833}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af9796c0ddd34bf385f9dec696801ba1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1342,
                  "height":833}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/资管产品列表-最近浏览/u0.jpg"}}]}},
  "masters":{
},
  "objectPaths":{
    "468f6bb9ab5948a286beddbf398d580e":{
      "scriptId":"u0"},
    "af9796c0ddd34bf385f9dec696801ba1":{
      "scriptId":"u1"}}});