$axure.loadCurrentPage({
  "url":"预约-登录.html",
  "generationDate":new Date(1403073214508.24),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"2c1e840bff0a44ff9072fec0d12b6d93",
    "type":"Axure:Page",
    "name":"预约-登录",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"cc87239da7fc4cf9835fb2f7b7879eb9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1342,
              "height":887}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2de74bcdb42b4f29942b31bc9d1be683",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1342,
                  "height":887}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预约-登录/u0.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "cc87239da7fc4cf9835fb2f7b7879eb9":{
      "scriptId":"u0"},
    "2de74bcdb42b4f29942b31bc9d1be683":{
      "scriptId":"u1"}}});