$axure.loadCurrentPage({
  "url":"购物车.html",
  "generationDate":new Date(1403073206902.8),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"764884a663b14e2d82c30b0d2205664d",
    "type":"Axure:Page",
    "name":"购物车",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"814606038f734978a7f973e1871bb9bb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1342,
              "height":1783}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d89a21d88cf74d9bb8cfaf109fef84a2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1342,
                  "height":1783}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购物车/u0.jpg"}}]}},
  "masters":{
},
  "objectPaths":{
    "814606038f734978a7f973e1871bb9bb":{
      "scriptId":"u0"},
    "d89a21d88cf74d9bb8cfaf109fef84a2":{
      "scriptId":"u1"}}});