$axure.loadCurrentPage({
  "url":"资管研究-日报.html",
  "generationDate":new Date(1403073201741.51),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b4017d9523c245c1a442d64ca3df99f0",
    "type":"Axure:Page",
    "name":"资管研究-日报",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"8b4ca9eb14c247cfbda32ca201869857",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1342,
              "height":3013}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"92723b3bd02a443184335b6107a9ad4a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1342,
                  "height":3013}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/资管研究-日报/u0.jpg"}}]}},
  "masters":{
},
  "objectPaths":{
    "8b4ca9eb14c247cfbda32ca201869857":{
      "scriptId":"u0"},
    "92723b3bd02a443184335b6107a9ad4a":{
      "scriptId":"u1"}}});